version: '3.8'
name: skillcraftrpg-app
services:
  skillcraftrpg_app_backend:
    build:
      context: ./backend
      dockerfile: /src/SkillCraft/Dockerfile
    image: skillcraftrpg_app_backend
    container_name: SkillCraft_backend
    # depends_on:
    #   - skillcraft_mssql
    restart: unless-stopped
    environment:
      ASPNETCORE_Environment: Development
    ports:
      - 8088:8080
