version: "3.8"
name: skillcraft
services:
  skillcraft_postgres:
    image: postgres
    container_name: SkillCraft_postgres
    environment:
      POSTGRES_PASSWORD: veg37TPkBDGC85HJ
    ports:
      - 5438:5432

  skillcraft_portal:
    image: fpion/portal:v4.0.0
    container_name: SkillCraft_portal
    depends_on:
      - skillcraft_postgres
    restart: unless-stopped
    environment:
      DatabaseProvider: EntityFrameworkCorePostgreSQL
      EnableBasicAuthentication: "true"
      EnableMigrations: "true"
      POSTGRESQLCONNSTR_Portal: "User ID=postgres;Password=veg37TPkBDGC85HJ;Host=skillcraft_postgres;Port=5432;Database=Portal;"
    ports:
      - 8888:8080

  skillcraft_backend:
    build:
      context: ./backend
      dockerfile: /src/SkillCraft/Dockerfile
    image: skillcraft_backend
    container_name: SkillCraft_backend
    depends_on:
      - skillcraft_postgres
    restart: unless-stopped
    environment:
      ASPNETCORE_Environment: Development
      DatabaseProvider: EntityFrameworkCorePostgreSQL
      Portal:BaseUrl: http://skillcraft_portal:8080
      POSTGRESQLCONNSTR_SkillCraft: "User ID=postgres;Password=veg37TPkBDGC85HJ;Host=skillcraft_postgres;Port=5432;Database=SkillCraft;"
    ports:
      - 8088:8080
