import type { App } from "vue";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faAdjust,
  faArrowLeft,
  faArrowRight,
  faArrowRightFromBracket,
  faArrowRightToBracket,
  faArrowsRotate,
  faArrowUp,
  faBan,
  faCheck,
  faClockRotateLeft,
  faCommentSms,
  faDesktop,
  faDice,
  faDungeon,
  faEdit,
  faEnvelope,
  faFloppyDisk,
  faGlobe,
  faHatWizard,
  faHome,
  faIdCard,
  faMagnifyingGlass,
  faMobile,
  faMoon,
  faNetworkWired,
  faPlus,
  faScroll,
  faSun,
  faTablet,
  faUser,
  faVial,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faAdjust,
  faArrowLeft,
  faArrowRight,
  faArrowRightFromBracket,
  faArrowRightToBracket,
  faArrowUp,
  faArrowsRotate,
  faBan,
  faCheck,
  faClockRotateLeft,
  faCommentSms,
  faDesktop,
  faDice,
  faDungeon,
  faEdit,
  faEnvelope,
  faFloppyDisk,
  faGlobe,
  faHatWizard,
  faHome,
  faIdCard,
  faMagnifyingGlass,
  faMobile,
  faMoon,
  faNetworkWired,
  faPlus,
  faScroll,
  faSun,
  faTablet,
  faUser,
  faVial,
  faXmark,
);

export default function (app: App) {
  app.component("font-awesome-icon", FontAwesomeIcon);
}
