import type { App } from "vue";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faAdjust,
  faArrowLeft,
  faArrowRight,
  faArrowRightFromBracket,
  faArrowRightToBracket,
  faArrowRotateLeft,
  faArrowUp,
  faArrowsRotate,
  faBan,
  faCartShopping,
  faCheck,
  faCircleArrowUp,
  faCirclePlus,
  faClockRotateLeft,
  faCodeBranch,
  faCoins,
  faCommentSms,
  faDesktop,
  faDice,
  faDownload,
  faDungeon,
  faEdit,
  faEnvelope,
  faFloppyDisk,
  faGraduationCap,
  faHatWizard,
  faHome,
  faIdCard,
  faKey,
  faKitchenSet,
  faLanguage,
  faMagnifyingGlass,
  faMobile,
  faMoon,
  faNetworkWired,
  faPaw,
  faPlus,
  faRobot,
  faRulerVertical,
  faScrewdriverWrench,
  faScroll,
  faSun,
  faTablet,
  faTag,
  faTrophy,
  faUser,
  faVial,
  faWandSparkles,
  faWeightHanging,
  faWheelchair,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

import { faCircle, faCircleCheck, faSquare, faSquareCheck } from "@fortawesome/free-regular-svg-icons";

library.add(
  faAdjust,
  faArrowLeft,
  faArrowRight,
  faArrowRightFromBracket,
  faArrowRightToBracket,
  faArrowRotateLeft,
  faArrowUp,
  faArrowsRotate,
  faBan,
  faCartShopping,
  faCheck,
  faCircle,
  faCircleArrowUp,
  faCircleCheck,
  faCircleCheck,
  faCirclePlus,
  faClockRotateLeft,
  faCodeBranch,
  faCoins,
  faCommentSms,
  faDesktop,
  faDice,
  faDownload,
  faDungeon,
  faEdit,
  faEnvelope,
  faFloppyDisk,
  faGraduationCap,
  faHatWizard,
  faHome,
  faIdCard,
  faKey,
  faKitchenSet,
  faLanguage,
  faMagnifyingGlass,
  faMobile,
  faMoon,
  faNetworkWired,
  faPaw,
  faPlus,
  faRobot,
  faRulerVertical,
  faScrewdriverWrench,
  faScroll,
  faSquare,
  faSquareCheck,
  faSun,
  faTablet,
  faTag,
  faTrophy,
  faUser,
  faVial,
  faWandSparkles,
  faWeightHanging,
  faWheelchair,
  faXmark,
);

export default function (app: App) {
  app.component("font-awesome-icon", FontAwesomeIcon);
}
